usecase-beta
direction LR
actor Personnel

Personnel --> "consulter le tableau de bord"
Personnel --> "gérer les consultations"
Personnel --> "gérer les spécialités"
Personnel --> "gérer les ordonnances"
Personnel --> "gérer les patients"
